security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_customer_provider:
            entity:
                class: App\Entity\Customer
                property: email
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        app_users:
            chain:
                providers: ['app_customer_provider', 'app_user_provider']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        user:
            pattern: ^/edition
            # context: user
            # lazy: true
            provider: app_user_provider
            # anonymous: ~
            form_login:
                login_path: /edition/login
                check_path: /edition/login
                default_target_path: /edition/login
                username_parameter: email
                password_parameter: password
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            entry_point: App\Security\AppUserAuthenticator
        customer:
            pattern: ^/
            # context: customer
            # lazy: true
            # anonymous: ~
            provider: app_customer_provider
            entry_point: form_login
            form_login:
                login_path: /connexion
                default_target_path: /connexion
                username_parameter: email
                password_parameter: password
            custom_authenticator: App\Security\AppCustomerAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            # remember_me:
            #     secret: '%kernel.secret%'
            #     lifetime: 604800
            #     path: /
            # entry_point: App\Security\AppCustomerAuthenticator
            # # pattern: ^/connexion
            # form_login:
            #     login_path: app_customer_login
            #     check_path: app_customer_login
            #     enable_csrf: true
    access_control:
        - { path: ^/edition/login, roles: PUBLIC_ACCESS }
        # require ROLE_ADMIN or ROLE_EDITOR for /admin*
        - { path: '^/edition', roles: ROLE_EDITOR }
    role_hierarchy:
        ROLE_EDITOR:       ROLE_USER
        ROLE_ADMIN: [ROLE_EDITOR]



when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
